### ISSUE TITLE
Demo page is down

### ISSUE THREAD

**Issue by gkindrick** [jxnblk/colorable#28]
I didn't realize what an important part of my work Colorable has become until I couldn't access the [demo page](https://colorable.jxnblk.com) today. I hope this is a temporary hiccup, not a step toward retiring such a wonderful tool, and what I consider the finest color tester for ADA-compliance available. 
![screenshot 2019-01-13 at 4 25 03 pm](https://user-images.githubusercontent.com/903448/51092756-cff05480-174f-11e9-9f47-5553eb6d4bc9.png)

**Comment by jxnblk** [comment]
I switched DNS providers and haven't re-verified with Zeit Now yet. I'll try to get it back online later this evening

**Comment by gkindrick** [comment]
Whew! Glad to hear it. Thanks.

Side note: I love your color matrix tool too. Please keep that alive forever.

**Comment by TheeMattOliver** [comment]
Agree. Glad to see it's back online!
