### ISSUE TITLE
How can I add the color of your Text Demo to the text of my own website?

### ISSUE THREAD

**Issue by Brian1111** [jxnblk/colorable#31]
I installed colorable using npm. I want to add the same text and background color that are in your Text Demo to my own website, but I just can't figure out how to do it?

**Comment by Brian1111** [comment]
I installed colorable using npm.  I want to add the same text and background color in your Text Demo to my own website, but I just can't figure out how to do it?

**Comment by jxnblk** [comment]
Hi! The npm package is for comparing arrays of colors and getting color contrast data. If you want to use the colors from the site, you can copy and paste the values from the site into your CSS or styles

**Comment by Brian1111** [comment]
Thanks for info.  I close the issue.
