### ISSUE TITLE
Color Fail

### ISSUE THREAD

**Issue by geoffthibeau** [jxnblk/colorable#4]
Love the tool, but have to point out that your colors fail:
The menu/filter at the top right, specifically.
http://jxnblk.com/colorable/?mode=app&colors=%23304650.%230089FF

![screen shot 2015-04-14 at 14 20 48](https://cloud.githubusercontent.com/assets/1915972/7145395/a3162952-e2b1-11e4-8459-811bc883601c.png)

Using `#fff` will resolve the issue.

**Comment by jxnblk** [comment]
Thanks :)
